# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

pod 'SwiftyJSON', '~> 3.1.4'
pod 'Alamofire', '~> 4.4'
pod 'Kingfisher', '~> 3.11.0'
pod 'ObjectMapper', '~> 2.2.8'
pod 'RxSwift'

target 'PlaywingsTest'
